print("========================")
a = int(input("Masukkan Nilai a "))
b = int(input("Masukkan Nilai b "))
c =int(input("Masukkan Nilai c "))
print("========================")
print("Perhitungan (a+b)*(a-c)")
print("a:",a)
print("b:",b)
print("c:",c)
print("Hasil dari (a+b)(a-c) :", (a+b)*(a-c))
print("========================")

print("========================")
a = int(input("Masukkan Nilai a "))
b= int(input("Masukkan Nilai b "))
c = int(input("Masukkan Nilai c "))
print("========================")
print("Perhitungan( a*b)/(a+c)")
print("a:",a)
print("b:",b)
print("c:",c)
print("Hasil dari (a*b) /(a+c) adalah :",(a*b)/(a+c))
print("========================")


print("========================")
a = int(input("Masukkan Nilai a "))
b = int(input("Masukkan Nilai b "))
t = int(input("Masukkan Nilai t "))
print("========================")
print("Perhitungan Luas Trapesium")
print("a:",a)
print("b:",b)
print("t:",t) 
print("Rumus trapesium yaitu 1/2*(a+b)*t")
print("Jadi hasil dari luas trapesium adalah:",1/2*(a+b)*t) 
print("========================")


print("========================")
r = int(input("Masukkan Nilai r "))
print("Perhitungan Keliling Lingkaran")
print("r:",r)
print("Rumus keliling lingkaran yaitu 2πr")
print("keliling lingkaran adalah:",2*3.14*r)
print("========================")
